export const blogsData = [
  {
    id: 1,
    title: "html",
    body: "Voluptua sit lorem labore accusam dolores sit ea et. Consetetur accusam sed voluptua voluptua rebum gubergren, sed eirmod no takimata magna sadipscing takimata magna invidunt dolor, amet diam lorem at sea diam nonumy, at lorem voluptua takimata sed stet lorem eirmod gubergren, aliquyam sed sed justo sit. Tempor sadipscing sed accusam no est. Est eirmod diam lorem diam vero, elitr tempor dolor sanctus sed clita et takimata dolores takimata. Gubergren lorem erat ut elitr, dolore duo et ipsum labore. Magna eos nonumy eos et ut. Erat lorem eirmod voluptua et et nonumy et takimata elitr, kasd sea vero ipsum diam sed sanctus. Labore sed ipsum nonumy lorem et accusam, magna diam invidunt consetetur sea eirmod amet tempor no ea, consetetur vero labore consetetur eos kasd, aliquyam duo at dolor invidunt, et justo erat nonumy est. Rebum aliquyam sadipscing diam no, et sadipscing elitr invidunt sadipscing amet, clita ut elitr sed et sit no ipsum sanctus, et vero stet amet at, at ipsum diam dolor eirmod amet. Dolor lorem et sed ut et sanctus sea, justo sed et et dolore est est est takimata magna, lorem diam gubergren at at dolor tempor et magna, labore labore et sed erat amet, vero est lorem diam lorem ut kasd, elitr no et duo et ipsum. Aliquyam et voluptua voluptua tempor et. Sit voluptua sed est dolores amet ipsum et, labore erat amet invidunt nonumy duo diam. Takimata tempor est est sed takimata tempor justo est et, ut et sed diam gubergren et at eos sadipscing justo. Dolor invidunt sed aliquyam dolor lorem magna. No sadipscing sed dolore rebum duo. Stet stet lorem dolores consetetur at ea elitr. Sea amet amet et et. Kasd est labore rebum takimata est sanctus sed labore. Accusam amet clita tempor consetetur sea et diam est lorem. Accusam eirmod amet ipsum nonumy. Sea sed sed sea diam. Ea lorem lorem accusam sadipscing aliquyam kasd consetetur. Ipsum ipsum consetetur ipsum invidunt, lorem stet labore est et ea ut ipsum stet, et sed amet.",
  },
  {
    id: 2,
    title: "css",
    body: "Voluptua sit lorem labore accusam dolores sit ea et. Consetetur accusam sed voluptua voluptua rebum gubergren, sed eirmod no takimata magna sadipscing takimata magna invidunt dolor, amet diam lorem at sea diam nonumy, at lorem voluptua takimata sed stet lorem eirmod gubergren, aliquyam sed sed justo sit. Tempor sadipscing sed accusam no est. Est eirmod diam lorem diam vero, elitr tempor dolor sanctus sed clita et takimata dolores takimata. Gubergren lorem erat ut elitr, dolore duo et ipsum labore. Magna eos nonumy eos et ut. Erat lorem eirmod voluptua et et nonumy et takimata elitr, kasd sea vero ipsum diam sed sanctus. Labore sed ipsum nonumy lorem et accusam, magna diam invidunt consetetur sea eirmod amet tempor no ea, consetetur vero labore consetetur eos kasd, aliquyam duo at dolor invidunt, et justo erat nonumy est. Rebum aliquyam sadipscing diam no, et sadipscing elitr invidunt sadipscing amet, clita ut elitr sed et sit no ipsum sanctus, et vero stet amet at, at ipsum diam dolor eirmod amet. Dolor lorem et sed ut et sanctus sea, justo sed et et dolore est est est takimata magna, lorem diam gubergren at at dolor tempor et magna, labore labore et sed erat amet, vero est lorem diam lorem ut kasd, elitr no et duo et ipsum. Aliquyam et voluptua voluptua tempor et. Sit voluptua sed est dolores amet ipsum et, labore erat amet invidunt nonumy duo diam. Takimata tempor est est sed takimata tempor justo est et, ut et sed diam gubergren et at eos sadipscing justo. Dolor invidunt sed aliquyam dolor lorem magna. No sadipscing sed dolore rebum duo. Stet stet lorem dolores consetetur at ea elitr. Sea amet amet et et. Kasd est labore rebum takimata est sanctus sed labore. Accusam amet clita tempor consetetur sea et diam est lorem. Accusam eirmod amet ipsum nonumy. Sea sed sed sea diam. Ea lorem lorem accusam sadipscing aliquyam kasd consetetur. Ipsum ipsum consetetur ipsum invidunt, lorem stet labore est et ea ut ipsum stet, et sed amet.",
  },
  {
    id: 3,
    title: "bootstrap",
    body: "Voluptua sit lorem labore accusam dolores sit ea et. Consetetur accusam sed voluptua voluptua rebum gubergren, sed eirmod no takimata magna sadipscing takimata magna invidunt dolor, amet diam lorem at sea diam nonumy, at lorem voluptua takimata sed stet lorem eirmod gubergren, aliquyam sed sed justo sit. Tempor sadipscing sed accusam no est. Est eirmod diam lorem diam vero, elitr tempor dolor sanctus sed clita et takimata dolores takimata. Gubergren lorem erat ut elitr, dolore duo et ipsum labore. Magna eos nonumy eos et ut. Erat lorem eirmod voluptua et et nonumy et takimata elitr, kasd sea vero ipsum diam sed sanctus. Labore sed ipsum nonumy lorem et accusam, magna diam invidunt consetetur sea eirmod amet tempor no ea, consetetur vero labore consetetur eos kasd, aliquyam duo at dolor invidunt, et justo erat nonumy est. Rebum aliquyam sadipscing diam no, et sadipscing elitr invidunt sadipscing amet, clita ut elitr sed et sit no ipsum sanctus, et vero stet amet at, at ipsum diam dolor eirmod amet. Dolor lorem et sed ut et sanctus sea, justo sed et et dolore est est est takimata magna, lorem diam gubergren at at dolor tempor et magna, labore labore et sed erat amet, vero est lorem diam lorem ut kasd, elitr no et duo et ipsum. Aliquyam et voluptua voluptua tempor et. Sit voluptua sed est dolores amet ipsum et, labore erat amet invidunt nonumy duo diam. Takimata tempor est est sed takimata tempor justo est et, ut et sed diam gubergren et at eos sadipscing justo. Dolor invidunt sed aliquyam dolor lorem magna. No sadipscing sed dolore rebum duo. Stet stet lorem dolores consetetur at ea elitr. Sea amet amet et et. Kasd est labore rebum takimata est sanctus sed labore. Accusam amet clita tempor consetetur sea et diam est lorem. Accusam eirmod amet ipsum nonumy. Sea sed sed sea diam. Ea lorem lorem accusam sadipscing aliquyam kasd consetetur. Ipsum ipsum consetetur ipsum invidunt, lorem stet labore est et ea ut ipsum stet, et sed amet.",
  },
  {
    id: 4,
    title: "sass",
    body: "Voluptua sit lorem labore accusam dolores sit ea et. Consetetur accusam sed voluptua voluptua rebum gubergren, sed eirmod no takimata magna sadipscing takimata magna invidunt dolor, amet diam lorem at sea diam nonumy, at lorem voluptua takimata sed stet lorem eirmod gubergren, aliquyam sed sed justo sit. Tempor sadipscing sed accusam no est. Est eirmod diam lorem diam vero, elitr tempor dolor sanctus sed clita et takimata dolores takimata. Gubergren lorem erat ut elitr, dolore duo et ipsum labore. Magna eos nonumy eos et ut. Erat lorem eirmod voluptua et et nonumy et takimata elitr, kasd sea vero ipsum diam sed sanctus. Labore sed ipsum nonumy lorem et accusam, magna diam invidunt consetetur sea eirmod amet tempor no ea, consetetur vero labore consetetur eos kasd, aliquyam duo at dolor invidunt, et justo erat nonumy est. Rebum aliquyam sadipscing diam no, et sadipscing elitr invidunt sadipscing amet, clita ut elitr sed et sit no ipsum sanctus, et vero stet amet at, at ipsum diam dolor eirmod amet. Dolor lorem et sed ut et sanctus sea, justo sed et et dolore est est est takimata magna, lorem diam gubergren at at dolor tempor et magna, labore labore et sed erat amet, vero est lorem diam lorem ut kasd, elitr no et duo et ipsum. Aliquyam et voluptua voluptua tempor et. Sit voluptua sed est dolores amet ipsum et, labore erat amet invidunt nonumy duo diam. Takimata tempor est est sed takimata tempor justo est et, ut et sed diam gubergren et at eos sadipscing justo. Dolor invidunt sed aliquyam dolor lorem magna. No sadipscing sed dolore rebum duo. Stet stet lorem dolores consetetur at ea elitr. Sea amet amet et et. Kasd est labore rebum takimata est sanctus sed labore. Accusam amet clita tempor consetetur sea et diam est lorem. Accusam eirmod amet ipsum nonumy. Sea sed sed sea diam. Ea lorem lorem accusam sadipscing aliquyam kasd consetetur. Ipsum ipsum consetetur ipsum invidunt, lorem stet labore est et ea ut ipsum stet, et sed amet.",
  },
  {
    id: 5,
    title: "javascript",
    body: "Voluptua sit lorem labore accusam dolores sit ea et. Consetetur accusam sed voluptua voluptua rebum gubergren, sed eirmod no takimata magna sadipscing takimata magna invidunt dolor, amet diam lorem at sea diam nonumy, at lorem voluptua takimata sed stet lorem eirmod gubergren, aliquyam sed sed justo sit. Tempor sadipscing sed accusam no est. Est eirmod diam lorem diam vero, elitr tempor dolor sanctus sed clita et takimata dolores takimata. Gubergren lorem erat ut elitr, dolore duo et ipsum labore. Magna eos nonumy eos et ut. Erat lorem eirmod voluptua et et nonumy et takimata elitr, kasd sea vero ipsum diam sed sanctus. Labore sed ipsum nonumy lorem et accusam, magna diam invidunt consetetur sea eirmod amet tempor no ea, consetetur vero labore consetetur eos kasd, aliquyam duo at dolor invidunt, et justo erat nonumy est. Rebum aliquyam sadipscing diam no, et sadipscing elitr invidunt sadipscing amet, clita ut elitr sed et sit no ipsum sanctus, et vero stet amet at, at ipsum diam dolor eirmod amet. Dolor lorem et sed ut et sanctus sea, justo sed et et dolore est est est takimata magna, lorem diam gubergren at at dolor tempor et magna, labore labore et sed erat amet, vero est lorem diam lorem ut kasd, elitr no et duo et ipsum. Aliquyam et voluptua voluptua tempor et. Sit voluptua sed est dolores amet ipsum et, labore erat amet invidunt nonumy duo diam. Takimata tempor est est sed takimata tempor justo est et, ut et sed diam gubergren et at eos sadipscing justo. Dolor invidunt sed aliquyam dolor lorem magna. No sadipscing sed dolore rebum duo. Stet stet lorem dolores consetetur at ea elitr. Sea amet amet et et. Kasd est labore rebum takimata est sanctus sed labore. Accusam amet clita tempor consetetur sea et diam est lorem. Accusam eirmod amet ipsum nonumy. Sea sed sed sea diam. Ea lorem lorem accusam sadipscing aliquyam kasd consetetur. Ipsum ipsum consetetur ipsum invidunt, lorem stet labore est et ea ut ipsum stet, et sed amet.",
  },
];
